apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    tier: web-app
spec:
  containers:
  - name: nginx
    image: nginx:1.25.4
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: Web-Server
spec:
  selector:
    app: httpd
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80