apiVersion: v1
kind: Pod
metadata:
  name: mybackendapp
  labels:
    tier: backend-app
spec:
  containers:
  - name: nginx
    image: nginx:1.25.4
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    tier: redis
spec:
  nodeName: node01
  containers:
  - name: nginx
    image: nginx:1.25.4
    ports:
    - containerPort: 443
