apiVersion: v1
kind: Pod
metadata:
  name: super-busy-box
  namespace: dev
spec:
    containers:
    - name: busy-bee
      image: busybox:latest
      command: ["/bin/sh"]
      args: ["-c", "sleep 3600"]

---
apiVersion: batch/v1
kind: Job
metadata:
  name: busy-job
  namespace: maintenance
spec:
  template:
    metadata:
      name: jobber
      namespace: maintenance
    spec:
      containers:
      - name: job-pod
        image: nginx:latest
      restartPolicy: Never

---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
    - name: app-server
      image: nginx:latest


