apiVersion: v1
kind: Pod
metadata:
  name:
    downward-api-vol-example
  labels:
    region: us-east-2
    temperature: F
    distance: miles
  annotations:
    tool: killercoda
    alt-tool: k8slibrary
spec:
  containers:
    - name: busy-container
      image: busybox:latest
      command: ["sh", "-c"]
      args:
      - while true; do
          if [[ -e /etc/podinfo/labels ]]; then
            echo -en '\n\n'; cat /etc/podinfo/labels; fi;
          if [[ -e /etc/podinfo/annotations ]]; then
            echo -en '\n\n'; cat /etc/podinfo/annotations; fi;
          sleep 5;
        done;
      volumeMounts:
        - name: downward-volume
          mountPath: /etc/podinfo
  volumes:
     - name: downward-volume
       downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations

