apiVersion: v1:
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: Pod
metadata:
  name: memory-pod
  labels:
    memoryRequests: true
    memoryLimits: true
    singleContainer: true
spec:
  containers:
    - name: web-server
      image: nginx:latest
      resources:
        limits:
          memory: 500Mi
        requests:
          memory: 250Mi
---
