# Task : https://kubernetes.io/docs/tasks/run-application/run-single-instance-stateful-application/
apiVersion: v1
kind: ConfigMap
metadata:
  name: sql-admin-data
data:
  MYSQL_ROOT_PASSWORD: admin
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    tier: db-vol
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  local:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pet-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:  
    requests:
      storage: "1G"
  selector:
    matchLabels:
      tier: db-vol
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 2
  selector:
    matchLabels: 
      tier: db-cluster
  template:
    metadata:
      name: my-sql-app
      labels:
        tier: db-cluster
    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: mysql-vol
              mountPath: /var/lib/mysql
      volumes: 
        - name: mysql-vol
          persistentVolumeClaim:
            claimName: pet-pvc
---