apiVersion: v1
kind: Pod
metadata:
  name: windows-pod
  labels:
    windowsPod: "1"
    windows: open
spec:
  securityContext:
    runAsUser: "PodAdmin"
  containers:
    name: windows-pod-1
    image: nginx:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      tier: web
  template:
    metadata:
      name: web-app-pod
      labels:
        tier: web
    spec:
      containers:
        - name: nginx-c
          image: nginx:latest
---