apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /etc/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc1
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 500Mi
  volumeName: local-pv1
---
apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  containers:
    - name: web-server
      image: nginx:latest
      volumeMounts: 
        - name: my-secret-volume
          mountPath: /etc/data/secrets
  volumes:
    - name: my-secret-volume
      persistentVolumeClaim: 
        claimName: local-pvc1
