apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  username: YWRtaW4=
  password: c3VwZXJzZWNyZXQ=

---
## Accessing Secrets through a volume
apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  containers:
    - name: webserver
      image: nginx:latest
      volumeMounts:
        - name: my-secret-volume
          mountPath: /etc/secrets
      envFrom:
        - secretRef:
            name: sql-params
      env:
        - name: hostName
          valueFrom:
            configMapKeyRef:
              key: dbhost
              name: myconfigmap
  volumes:
    - name: my-secret-volume
      secret:
        secretName: my-secret
        items:
         - key: username
           path: creds/un
         - key: password
           path: creds/pass

---
## Accessing Secrets through a volume
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
    - name: appserver
      image: nginx:latest
      volumeMounts:
        - name: my-app-secret-volume
          mountPath: /etc/secrets
        - name: my-empty-dir
          mountPath: /etc/emptydir
  volumes:
    - name: my-app-secret-volume
      projected:
        sources:
          - secret:
              name: my-secret
              items:
                - key: username
                  path: creds/un
                - key: password
                  path: creds/pass
          - configMap:
              name: db-config
    - name: my-empty-dir
---
