# apiVersion: v1
# kind: Secret
# metadata:
#   name: my-secret
# data:
#   username: YWRtaW4=
#   password: c3VwZXJzZWNyZXQ=
---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: web
# spec:
#   containers:
#     - name: web-server
#       image: nginx:latest
#       volumeMounts: 
#         - name: my-secret-volume
#           mountPath: /etc/secrets
#   volumes: 
#     - name: my-secret-volume
#       secret:
#         secretName: my-secret
---
apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  containers:
    - name: web-server
      image: nginx:latest
      volumeMounts: 
        - name: my-secret-volume
          mountPath: /etc/secrets
  volumes: 
    - name: my-secret-volume
      secret:
        secretName: my-secret
        items: 
          - key: username
            path: creds/un
          - key: password
            path: creds/pass
