apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-params
data:
  dbPassword: admin123
---
apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    tier: backend
spec:
  containers:
    - name: my-db
      image: mysql:lts
      envFrom:
        - configMapRef:
            name: mysql-params
