apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    tier: backend
spec:
  containers:
    - name: my-db
      image: mysql:lts
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: super123
---