apiVersion: v1
kind: Pod
metadata:
  name: front-end
spec:
  containers:
    - name: front-end-pod
      image: nginx:latest
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: back-end
spec:
  containers:
    - name: back-end-pod
      image: mysql:9.1.0
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: db-configs

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configs
data:
  MYSQL_ROOT_PASSWORD: admin
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-allows-ingress
spec:
  policyTypes:
    - Egress
    - Ingress
  ingress:
  - ports:
      - port: 3306
  podSelector:
    matchLabels:
      name: back-end
    
  
