apiVersion: v1
kind: Pod
metadata:
  name: front
spec:
  containers:
    - name: front-end
      image: nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: back
  labels:
    name: back
spec:
  containers:
    - name: back-end
      image: nginx:latest
      volumeMounts:
        - name: altindex
          mountPath: /usr/share/nginx/html
    - name: busy-base
      image: busybox:latest
      command: ["/bin/sh"]
      args: ["-c", "echo Hello from Nginx!... > /config/index.html && sleep 3600"]
      volumeMounts:
        - name: altindex
          mountPath: /config
  volumes:
    - name: altindex
---
apiVersion: v1
kind: Pod
metadata:
  name: base
spec:
  containers:
    - name: busy-base
      image: busybox:latest
      command: ["/bin/sh"]
      args: ["-c", "echo Hello from Nginx!... > /config/index.html && sleep 3600"]
      volumeMounts:
        - name: altindex
          mountPath: /config
  volumes:
    - name: altindex

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: my-net-pol
spec:
  policyTypes: ["Ingress"]
  ingress:
    - ports:
      - protocol: TCP
        port: 8080
  podSelector:
    matchLabels:
      name: back
