apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    env:
    - name: DB_HOST_NAME
      valueFrom:
       configMapKeyRef:
         name: db-config
         key: DB_HOST