apiVersion: v1
kind: Pod
metadata:
  name: env-pod-with-secret
  labels:
    name: myname
spec:
  containers:
    - name: my-busy-buddy
      image: busybox:latest
      command: ["/bin/sh", "-c", "sleep 3600"]
      envFrom:
        - secretRef:
            name: super-secret
---
apiVersion: v1
kind: Pod
metadata:
  name: single-env-pod-with-secret
  labels:
    name: myname
spec:
  containers:
    - name: my-single-busy-buddy
      image: busybox:latest
      command: ["/bin/sh", "-c", "sleep 3600"]
      env:
        - name: MY_SUPER_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: super-secret
        - name: MY_CI_USERNAME
          valueFrom:
            configMapKeyRef:
              key: myUserName
              name: my-non-secret-cm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-non-secret-cm
data:
  myUserName: ciUserName
---
apiVersion: v1
kind: Pod
metadata:
  name: prod-pod
spec:
  containers:
    - name: prod-busy-box
      image: busybox:latest
      command: ["/bin/sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secrets
  volumes:
    - name: secret-volume
      secret:
        secretName: prod-db-secret
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-busy-box
      image: busybox:latest
      command: ["/bin/sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secrets
  volumes:
    - name: secret-volume
      secret:
        secretName: test-db-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prod-user
secrets:
  - name: prod-db-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-user
secrets:
  - name: test-db-secret
---
apiVersion: v1
kind: Pod
metadata:
  name: prod-sa-env-pod
spec:
  serviceAccount: prod-user
  containers:
    - name: prod-sa-env-busy-box
      image: busybox:latest
      command: ["/bin/sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secrets
  volumes:
    - name: secret-volume
      secret:
        secretName: prod-db-secret
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv1
  labels:
    tier: app
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /etc/secrets
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc1
spec:
  accessModes:
    - ReadWriteMany
  volumeName: my-pv1
  storageClassName: ""
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      tier: app
---
apiVersion: v1
kind: Pod
metadata:
  name: prod-pod-using-pvc
spec:
  serviceAccount: prod-user
  containers:
    - name: prod-sa-env-busy-box
      image: busybox:latest
      command: ["/bin/sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secrets
  volumes:
    - name: secret-volume
      persistentVolumeClaim:
        claimName: my-pvc1
      secret:
        secretName: prod-db-secret