apiVersion: v1
kind: Pod
metadata:
  name: volumeMountedConfigPod
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    volumeMounts:
    - name: config
      mountPath: "/config"
      readOnly: true
  volumes:
    - name: config
      configMap:
        name: db-config
        items:
        - key: "DB_HOST"
          path: "DB_HOST"

