apiVersion: v1
kind: Pod
metadata:
  name: my-web-server
  labels:
    tier: web-layer
spec:
  os:
   name: linux
  containers:
  - name: httpd
    image: httpd:2.4
    ports:
    - containerPort: 80
