apiVersion: v1
kind: Pod
metadata:
  name: mybackendapp
  labels:
    tier: backend-app
spec:
  containers:
  - name: nginx
    image: nginx:1.25.4
    ports:
    - containerPort: 80
  nodeSelector:
    distype: ssd
