apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: my-test-rs
  labels:
    env: local
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: mycontainerapp
        image: nginx:1.14.2
        ports:
        - containerPort: 80