apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader-role3
  namespace: test
rules:
  - apiGroups: ["*"]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-role-binding3
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  name: pod-reader-role3
  kind: Role
subjects:
  - kind: ServiceAccount
    name: test-sa
    namespace: test
---