# Create one SA in Dev namespace
# Create one SA in maintenance namespace
# kubectl get pods -n maintenance --as dev-sa -> returns a forbidden error
# kubectl get pods -n maintenance --as system:serviceaccount:dev:dev-sa -> returns a forbidden error
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: maintenance-pod-reader
  namespace: maintenance
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: maintenance-pod-reader-rb
  namespace: maintenance
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: maintenance-pod-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: dev-sa
    namespace: dev
---