apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    env: dev
    region: home-env
  annotations:
    kubernetes.io/change-cause: Initial deployment
spec:
  replicas: 3 
  selector:
    matchLabels:
      region: home
  template:
    metadata:
      labels:
        region: home
        purpose: learn
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
