apiVersion: v1
kind: Pod
metadata:
  name: proxy
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-web-service
spec:
  selector:
    name: proxy
  ports:
  - name: name-of-service-port
    port: 80
    targetPort: 80

